config/routes.rb
Exam::Application.routes.draw do
  devise_for :users

  root :to => 'pages#index'

  match 'dashboard'    => 'dashboard#index',    :as => :dashboard_index
  scope 'account' do
    match 'pay'    => 'account#pay',    :as => :account_pay # to handle Robokassa push request
  end
  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid # to handle Robokassa push request
    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail # to handle Robokassa fail redirect
  end
  match 'about'    => 'pages#about'
  match ':controller(/:action(/:id))(.:format)'
  match '*url' => 'pages#show', :constraints => lambda{|request|
    !request.path.starts_with?("/admin") # excluded if typus will be taking it...
  }
end

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>&copy; Exam 2012</p>
</footer>

</div>

</body>
</html>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= ss_title %></title>
  <meta content='<%= ss_keywords %>' name='keywords'>
  <meta content='<%= ss_description %>' name='description'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag( '/favicon.ico', :type => 'image/png' ) %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Exam</a>

      <div class="btn-group pull-right">
        <% if user_signed_in? %>
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <%= current_user.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(:dashboard), '/dashboard' %></li>
              <li class="divider"></li>
              <li><%= link_to t(:sign_out), destroy_user_session_path %></li>
            </ul>
        <% else %>
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i> <%= t :sign_in %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu header-login-form">
              <%= form_for( :user, :as => Devise.mappings[:user].name, :url => session_path(Devise.mappings[:user].name) ) do |f| %>

                  <%= f.email_field :email, :placeholder => "Email" %>
                  <%= f.password_field :password, :placeholder => t(:password) %>
                  <% if Devise.mappings[:user].rememberable? -%>
                    <%= f.hidden_field :remember_me, :value => 1 %>
                  <% end -%>

                  <%= f.submit t(:sign_in), :class => "btn btn-primary" %>
                  <%= link_to t(:sign_up), new_registration_path(Devise.mappings[:user].name) %><br />
              <% end %>
            </ul>

        <% end %>
      </div>
      <div class="nav-collapse">
        <%= render "shared/menu" %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">

app/views/shared/_menu.html.erb
<ul class="nav">
  <% Page.all.each do |item| -%>
      <li><a href="/<%= item.url %>"><%= item.title %></a></li>
  <% end %>
</ul>